
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    GA_ID: 'YOUR_GOOGLE_ANALYTICS_ID',
    base_url : 'https://api.dmkengwing.com'
  };
