
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    GA_ID: 'undefined',

   //base_url : 'http://127.0.0.1:8000'
    base_url : 'https://laravel-api.dmkengwing.com'
  };
