name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use Node.js 18.x or higher for Angular 17+

      - name: Create .env file
        run: |
          echo "GA_ID=${{ secrets.GA_ID }}" > .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          
      - name: Install dependencies
        run: npm ci # Use npm ci for faster installs and consistency in CI

      - name: Build Angular project
        run: npm run build -- --configuration=production # Ensure the correct build command

      - name: Run tests
        run: npm test
